version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pricescout
      MYSQL_USER: pricescout
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./apps/api/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=pricescout
      - DB_USER=pricescout
      - DB_PASSWORD=password
      - JWT_SECRET=your-jwt-secret
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    depends_on:
      - mysql
      - mailhog

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api

  ml-service:
    build:
      context: ./infra/ml-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production

volumes:
  mysql_data:
