version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: pricescout-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pricescout
      MYSQL_USER: pricescout
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./infra/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pricescout-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: pricescout-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - pricescout-network

  # ML Service (Python FastAPI)
  ml:
    build:
      context: ./infra/ml-service
      dockerfile: Dockerfile
    container_name: pricescout-ml
    ports:
      - "8081:8080"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - pricescout-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Service
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: pricescout-api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@mysql:3306/pricescout
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - CACHE_TTL=60
      - MAILHOG_HOST=mailhog
      - MAILHOG_PORT=1025
      - PREDICTOR_PROVIDER=prophet
      - ML_SERVICE_URL=http://ml:8080
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
      - AMAZON_RATE_LIMIT=10
      - EBAY_RATE_LIMIT=10
    depends_on:
      mysql:
        condition: service_healthy
      mailhog:
        condition: service_started
      ml:
        condition: service_healthy
    networks:
      - pricescout-network
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages/shared:/app/packages/shared
    command: pnpm dev

  # Web Frontend
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: pricescout-web
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api
    depends_on:
      - api
    networks:
      - pricescout-network
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages/shared:/app/packages/shared
    command: pnpm dev

volumes:
  mysql_data:
    driver: local

networks:
  pricescout-network:
    driver: bridge
